# Generated by Django 5.1 on 2024-08-14 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Support Agent'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
