# Generated by Django 5.1 on 2024-08-22 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_role_remove_user_role_user_roles'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='roles',
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.CharField(choices=[('customer', 'Customer'), ('agent', 'Support Agent'), ('admin', 'Admin')], default='customer', max_length=10),
        ),
    ]
