# Generated by Django 5.1 on 2024-08-22 18:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_remove_user_roles_user_roles'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Role',
        ),
    ]
