# Generated by Django 5.1 on 2024-08-22 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_delete_role'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='roles',
            new_name='role',
        ),
    ]
