# Generated by Django 5.1 on 2024-08-22 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='tags',
        ),
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
