# Generated by Django 5.1 on 2024-08-23 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_comment_resovled'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ticket',
            name='resolution',
        ),
    ]
