# Generated by Django 5.1 on 2024-08-31 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_rename_resovled_comment_the_fix'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='the_fix',
        ),
        migrations.AddField(
            model_name='ticket',
            name='cause',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='fix',
            field=models.TextField(blank=True, null=True),
        ),
    ]
