# Generated by Django 5.1 on 2024-09-28 08:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_remove_comment_the_fix_ticket_cause_ticket_fix'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='fix',
            new_name='resolution',
        ),
    ]
