# Generated by Django 5.1 on 2024-09-28 10:08

import tickets.tasks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_remove_ticket_cause_remove_ticket_resolution_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ref',
            field=models.CharField(default=tickets.tasks.generate_short_id, editable=False, max_length=8, null=True),
        ),
        migrations.AddField(
            model_name='ticket',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, null=True, unique=True),
        ),
    ]
