# Generated by Django 5.1 on 2024-09-28 10:09

import tickets.tasks
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0014_ticket_ref_ticket_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ref',
            field=models.CharField(default=tickets.tasks.generate_short_id, editable=False, max_length=8, null=True, unique=True),
        ),
    ]
