# Generated by Django 5.1 on 2024-09-28 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_rename_author_comment_created_by_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='content',
            new_name='comment',
        ),
    ]
