# Generated by Django 5.1.1 on 2024-10-09 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_alter_ticketassignment_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-created_at']},
        ),
        migrations.AlterModelOptions(
            name='ticket',
            options={'ordering': ['-created_at']},
        ),
    ]
